modLoader = "javafml"
loaderVersion = "[39,)"
license = "LGPL v3.0"
issueTrackerURL="https://github.com/PieKing1215/InvMoveCompat/issues"

[[mods]]
modId = "invmove_compat"
version = "${version}"
displayName = "InvMove Compat"
displayURL="https://github.com/PieKing1215/InvMoveCompat"
authors = "PieKing1215"
logoFile = "icon.png"
description = '''Mod compatibilities for InvMove.'''

[[dependencies.invmove_compat]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.invmove_compat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.invmove_compat]]
modId = "invmove"
mandatory = true
versionRange = "[0.8.0,)"
ordering = "BEFORE"
side = "CLIENT"