name: Build jars

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
        
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: build
        
    - name: Prep files
      run: |
        mv ./forge/build/libs/*[0-9].jar "./InvMoveCompats-forge-${{ steps.short-sha.outputs.sha }}.jar"
        mv ./fabric/build/libs/*[0-9].jar "./InvMoveCompats-fabric-${{ steps.short-sha.outputs.sha }}.jar"
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: "InvMoveCompats-forge-${{ steps.short-sha.outputs.sha }}"
        path: ./*forge*.jar

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: "InvMoveCompats-fabric-${{ steps.short-sha.outputs.sha }}"
        path: ./*fabric*.jar
