name: Build jars

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - uses: actions/checkout@v3
        with:
          repository: PieKing1215/InvMove
          path: "./InvMove/"

      - run: chmod +x ./InvMove/gradlew

      - name: publishCurrentToMavenLocal
        working-directory: ./InvMove
        run: ./gradlew publishCurrentToMavenLocal --no-daemon

      - uses: actions/checkout@v3

      - run: chmod +x ./gradlew

      - name: chiseledBuild
        run: ./gradlew chiseledBuild --no-daemon

      - name: Prep files
        run: |
          for f in ./build/libs/*.jar; do mv "$f" "$(echo "$f" | sed -E 's/(.+)-.+\+(.+)-(.+)/\1-${{ steps.short-sha.outputs.sha }}+\2-\3/')"; done

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "InvMoveCompats-build-${{ steps.short-sha.outputs.sha }}"
          path: ./build/libs
